from datetime import datetime
import hashlib
import re
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.core.config import get_live_secret_value, get_settings
from app.db.base import get_db
from app.models.cinode_credential import CinodeCredential
from app.models.cv_suggestion import CvSuggestion
from app.models.cv_variant import CvVariant
from app.models.profile_snapshot import ProfileSnapshot
from app.schemas.cinode_credential import (
    CinodeBrowserCreateCvRequest,
    CinodeBrowserCreateCvResponse,
    CinodeBrowserLoginResponse,
    CinodeBrowserPreflightRequest,
    CinodeBrowserPreflightResponse,
    CinodeConsultant,
    CinodeConsultantCvRequest,
    CinodeConsultantCvResponse,
    CinodeConsultantEnrichResponse,
    CinodeConsultantFetchRequest,
    CinodeConsultantsResponse,
    CinodeCredentialCreate,
    CinodeCredentialRead,
    CinodeCredentialTestResponse,
    CinodeResumePublicStatusResponse,
)
from app.services.cinode_browser_create_cv import (
    CinodeBrowserCreateCvError,
    create_cinode_cv_via_browser,
    login_cinode_browser_profile,
    preflight_cinode_resume_edit_access,
)
from app.services.consultant_enrichment import enrich_consultant_data
from app.services.cinode_client import build_docx_from_payload
from app.services.cinode_cv_docx import build_cinode_cv_docx
from app.services.cinode_browser_export import CinodeBrowserExportError, render_cv_page_to_pdf
from app.services.cinode_payload_mapper import build_cinode_payload
from app.services.cinode_directory import (
    CinodeApiError,
    check_public_resume_url,
    fetch_cinode_consultant_cv,
    fetch_cinode_consultants,
    mask_auth_value,
    normalize_auth_value,
    test_cinode_credential,
)

router = APIRouter(prefix="/cinode")


def _payload_fingerprint(text: str) -> str:
    value = (text or "").strip()
    if not value:
        return "empty"
    digest = hashlib.sha1(value.encode("utf-8")).hexdigest()[:10]
    preview = " ".join(value.split())[:40]
    return f"len={len(value)} sha1={digest} preview='{preview}'"


def _compose_presentation_text(payload: dict[str, Any]) -> str:
    summary = payload.get("summary")
    if isinstance(summary, str) and summary.strip():
        return summary.strip()[:12000]
    return ""


def _normalize_title_for_match(value: str) -> str:
    return " ".join((value or "").strip().lower().split())


def _ensure_unique_resume_title(title: str, resumes: list[dict[str, Any]] | None) -> str:
    wanted = (title or "").strip()
    if not wanted:
        return wanted
    existing: set[str] = set()
    for row in resumes or []:
        if not isinstance(row, dict):
            continue
        row_title = str(row.get("title") or "").strip()
        if row_title:
            existing.add(_normalize_title_for_match(row_title))
    wanted_key = _normalize_title_for_match(wanted)
    if wanted_key not in existing:
        return wanted
    suffix = datetime.now().strftime("%Y-%m-%d %H.%M.%S")
    return f"{wanted} ({suffix})"


def _collect_skill_terms_from_suggestions(suggestions: list[CvSuggestion]) -> list[str]:
    accepted = [s for s in suggestions if str(s.status or "").strip().lower() == "accepted"]
    skill_types = {
        "keyword",
        "skills",
        "skill",
        "tools",
        "tool",
        "techniques",
        "technique",
        "teknikker",
        "teknikk",
        "verktøy",
        "verktoy",
        "kompetanse",
    }
    raw_terms: list[str] = []
    for item in accepted:
        section = str(item.section_type or "").strip().lower()
        if section not in skill_types:
            continue
        text = str(item.suggested_text or "").strip()
        if not text:
            continue
        for chunk in re.split(r"[\n,;|]+", text):
            term = chunk.strip(" -•\t\r\n")
            if not term:
                continue
            raw_terms.append(term)

    def _normalize_skill_term(term: str) -> str:
        t = " ".join((term or "").split()).strip()
        low = t.lower()
        # Strip likely autogenerated noise suffixes, e.g. "skill21665174174146".
        # Keep normal version numbers like "C++20" or "ISO 27001" intact.
        def _strip_generated_suffix(value: str) -> str:
            txt = value.strip()
            # Case 1: explicit separator before a long numeric tail.
            m = re.match(r"^(.*?)[\s_\-]+\d{8,}$", txt)
            if m and m.group(1).strip():
                return m.group(1).strip()
            # Case 2: long numeric tail attached directly to letters.
            m2 = re.match(r"^(.*?[A-Za-zÆØÅæøå])\d{8,}$", txt)
            if m2 and m2.group(1).strip():
                return m2.group(1).strip()
            return txt

        t = _strip_generated_suffix(t)
        low = t.lower()
        if low.endswith("erfaring") and len(low) > len("erfaring") + 2:
            stem = t[: -len("erfaring")].strip(" -_/")
            if stem:
                t = stem
                low = t.lower()
        # Common Norwegian stem cleanup after stripping "...erfaring"
        # e.g. "programmerings" -> "programmering"
        if low.endswith("ings") and len(low) > 6:
            t = t[:-1]
            low = t.lower()
        if low == "programmerings":
            t = "Programmering"
            low = "programmering"
        # keep common preferred spelling for this project
        if low in {"claude code", "claude-code"}:
            t = "Claude-code"
        return t

    out: list[str] = []
    seen: set[str] = set()
    for term in raw_terms:
        normalized = _normalize_skill_term(term)
        norm = " ".join(normalized.split()).lower()
        if len(norm) < 2 or len(norm) > 80:
            continue
        if norm in seen:
            continue
        seen.add(norm)
        out.append(normalized)
    return out[:20]


def _extract_skills_from_selected_resume(resume_payload: dict[str, Any] | None) -> list[str]:
    if not isinstance(resume_payload, dict):
        return []
    resume = resume_payload.get("resume")
    if not isinstance(resume, dict):
        return []
    blocks = resume.get("blocks")
    if not isinstance(blocks, list):
        return []

    out: list[str] = []
    seen: set[str] = set()
    for block in blocks:
        if not isinstance(block, dict):
            continue
        if int(block.get("blockType") or 0) != 12:
            continue
        data = block.get("data")
        if not isinstance(data, list):
            continue
        for category in data:
            if not isinstance(category, dict):
                continue
            skills = category.get("skills")
            if not isinstance(skills, list):
                continue
            for skill in skills:
                if not isinstance(skill, dict):
                    continue
                name = str(skill.get("name") or "").strip()
                if not name:
                    continue
                key = name.lower()
                if key in seen:
                    continue
                seen.add(key)
                out.append(name)
    return out[:80]


def _to_read(item: CinodeCredential) -> CinodeCredentialRead:
    return CinodeCredentialRead(
        id=item.id,
        label=item.label,
        base_url=item.base_url,
        authorization_masked=mask_auth_value(item.auth_value),
        is_default=item.is_default,
        created_at=item.created_at,
        last_test_status=item.last_test_status,
        last_test_message=item.last_test_message,
        last_test_at=item.last_test_at,
    )


def _resolve_auth_value(row: CinodeCredential, token_override: str | None) -> str:
    override = (token_override or "").strip()
    if override:
        return normalize_auth_value(override)
    if (row.label or "").strip() == "Cinode (.env)":
        live = (get_live_secret_value("CINODE_API_TOKEN") or "").strip()
        if live:
            return normalize_auth_value(live)
    return row.auth_value


def _find_selected_resume_entry(consultant_data: dict[str, Any]) -> dict[str, Any] | None:
    selected_resume_id = consultant_data.get("selected_resume_id")
    resumes = consultant_data.get("resumes")
    if not isinstance(resumes, list):
        return None
    for entry in resumes:
        if not isinstance(entry, dict):
            continue
        entry_id = entry.get("id")
        try:
            if entry_id is not None and selected_resume_id is not None and int(entry_id) == int(selected_resume_id):
                return entry
        except Exception:
            continue
    return None


def _ensure_env_credential(db: Session) -> None:
    settings = get_settings()
    base_url = (settings.cinode_base_url or "").strip()
    raw_auth = (settings.cinode_api_token or "").strip()
    if not base_url or not raw_auth:
        return

    normalized_auth = normalize_auth_value(raw_auth)
    env_label = "Cinode (.env)"

    row = db.query(CinodeCredential).filter(CinodeCredential.label == env_label).first()
    if row:
        changed = False
        if row.base_url != base_url:
            row.base_url = base_url
            changed = True
        if row.auth_value != normalized_auth:
            row.auth_value = normalized_auth
            changed = True
        if not row.is_default:
            db.query(CinodeCredential).update({CinodeCredential.is_default: False})
            row.is_default = True
            changed = True
        if changed:
            db.commit()
        return

    db.query(CinodeCredential).update({CinodeCredential.is_default: False})
    row = CinodeCredential(
        label=env_label,
        base_url=base_url,
        auth_value=normalized_auth,
        is_default=True,
    )
    db.add(row)
    db.commit()


@router.get("/credentials", response_model=list[CinodeCredentialRead])
def list_credentials(db: Session = Depends(get_db)) -> list[CinodeCredentialRead]:
    _ensure_env_credential(db)
    rows = db.query(CinodeCredential).order_by(CinodeCredential.created_at.desc()).all()
    return [_to_read(row) for row in rows]


@router.post("/credentials", response_model=CinodeCredentialRead, status_code=201)
def create_credential(payload: CinodeCredentialCreate, db: Session = Depends(get_db)) -> CinodeCredentialRead:
    auth_value = normalize_auth_value(payload.authorization)

    if payload.is_default:
        db.query(CinodeCredential).update({CinodeCredential.is_default: False})

    row = CinodeCredential(
        label=payload.label.strip(),
        base_url=payload.base_url.strip(),
        auth_value=auth_value,
        is_default=payload.is_default,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return _to_read(row)


@router.delete("/credentials/{credential_id}", status_code=204)
def delete_credential(credential_id: str, db: Session = Depends(get_db)) -> None:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")

    db.delete(row)
    db.commit()


@router.post("/credentials/{credential_id}/set-default", response_model=CinodeCredentialRead)
def set_default_credential(credential_id: str, db: Session = Depends(get_db)) -> CinodeCredentialRead:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")

    db.query(CinodeCredential).update({CinodeCredential.is_default: False})
    row.is_default = True
    db.commit()
    db.refresh(row)
    return _to_read(row)


@router.post("/credentials/{credential_id}/test", response_model=CinodeCredentialTestResponse)
def test_credential(credential_id: str, db: Session = Depends(get_db)) -> CinodeCredentialTestResponse:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")

    ok, status_code, message, whoami = test_cinode_credential(row.base_url, row.auth_value)

    row.last_test_status = "ok" if ok else "failed"
    row.last_test_message = message[:1024]
    row.last_test_at = datetime.utcnow()
    db.commit()

    return CinodeCredentialTestResponse(
        credential_id=credential_id,
        ok=ok,
        status_code=status_code,
        message=message,
        whoami=whoami,
    )


@router.post("/credentials/{credential_id}/consultants", response_model=CinodeConsultantsResponse)
def get_consultants(
    credential_id: str,
    payload: CinodeConsultantFetchRequest,
    db: Session = Depends(get_db),
) -> CinodeConsultantsResponse:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, payload.cinode_token_override)

    try:
        (
            consultants,
            source_path,
            company_id,
            restricted_to_self,
            current_user_id,
            current_user_name,
            access_reason,
        ) = fetch_cinode_consultants(
            base_url=row.base_url,
            auth_value=auth_value,
            oslo_only=payload.oslo_only,
            limit=payload.limit,
            path_override=payload.path_override,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return CinodeConsultantsResponse(
        credential_id=credential_id,
        source_path=source_path,
        company_id=company_id,
        restricted_to_self=restricted_to_self,
        current_user_id=current_user_id,
        current_user_name=current_user_name,
        access_reason=access_reason,
        total=len(consultants),
        consultants=[CinodeConsultant(**item) for item in consultants],
    )


@router.post("/credentials/{credential_id}/consultants/{consultant_id}/cv", response_model=CinodeConsultantCvResponse)
def get_consultant_cv(
    credential_id: str,
    consultant_id: str,
    payload: CinodeConsultantCvRequest,
    db: Session = Depends(get_db),
) -> CinodeConsultantCvResponse:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, payload.cinode_token_override)

    try:
        result = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=payload.resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return CinodeConsultantCvResponse(
        credential_id=credential_id,
        consultant_id=consultant_id,
        company_id=result["company_id"],
        source_path=result["source_path"],
        full_name=result["full_name"],
        email=result["email"],
        title=result["title"],
        location=result["location"],
        resumes=result["resumes"],
        selected_resume_id=result["selected_resume_id"],
        profile=result["profile"],
        resume=result["resume"],
    )


@router.get("/credentials/{credential_id}/consultants/{consultant_id}/cv.docx")
def download_consultant_cv_docx(
    credential_id: str,
    consultant_id: str,
    resume_id: int | None = None,
    token_override: str | None = None,
    db: Session = Depends(get_db),
) -> Response:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, token_override)

    try:
        result = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    docx_bytes = build_cinode_cv_docx(result["profile"], result["resume"])
    safe_name = result["full_name"].strip().replace(" ", "_") or f"consultant_{consultant_id}"
    filename = f"{safe_name}_cv.docx"
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return Response(
        content=docx_bytes,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers=headers,
    )


@router.get("/credentials/{credential_id}/consultants/{consultant_id}/cv.browser-pdf")
def download_consultant_cv_browser_pdf(
    credential_id: str,
    consultant_id: str,
    resume_id: int | None = None,
    prefer_public_url: bool = True,
    token_override: str | None = None,
    db: Session = Depends(get_db),
) -> Response:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, token_override)

    try:
        result = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    selected_resume_id = result.get("selected_resume_id")
    selected_resume: dict | None = None
    resumes = result.get("resumes")
    if isinstance(resumes, list):
        for item in resumes:
            if not isinstance(item, dict):
                continue
            item_id = item.get("id")
            if item_id is not None and selected_resume_id is not None and int(item_id) == int(selected_resume_id):
                selected_resume = item
                break
        if selected_resume is None and resumes:
            first = resumes[0]
            if isinstance(first, dict):
                selected_resume = first

    candidate_urls: list[str] = []
    if selected_resume:
        public_url = selected_resume.get("publicViewUrl")
        view_url = selected_resume.get("viewUrl")
        public_value = public_url.strip() if isinstance(public_url, str) else ""
        view_value = view_url.strip() if isinstance(view_url, str) else ""
        if prefer_public_url:
            if public_value:
                candidate_urls.append(public_value)
            if view_value and view_value not in candidate_urls:
                candidate_urls.append(view_value)
        else:
            if view_value:
                candidate_urls.append(view_value)
            if public_value and public_value not in candidate_urls:
                candidate_urls.append(public_value)

    if not candidate_urls:
        raise HTTPException(status_code=400, detail="Could not resolve resume view URL for browser export")

    last_error: str | None = None
    pdf_bytes: bytes | None = None
    for url in candidate_urls:
        try:
            pdf_bytes = render_cv_page_to_pdf(cv_url=url)
            break
        except CinodeBrowserExportError as exc:
            last_error = str(exc)

    if pdf_bytes is None:
        detail = last_error or "Browser export failed"
        detail += " (Tip: ensure the resume is shared as public/Anyone in Cinode for headless export.)"
        raise HTTPException(status_code=400, detail=detail)

    safe_name = result["full_name"].strip().replace(" ", "_") or f"consultant_{consultant_id}"
    filename = f"{safe_name}_cinode_layout.pdf"
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)


@router.get("/credentials/{credential_id}/consultants/{consultant_id}/public-status", response_model=CinodeResumePublicStatusResponse)
def get_consultant_resume_public_status(
    credential_id: str,
    consultant_id: str,
    resume_id: int | None = None,
    token_override: str | None = None,
    db: Session = Depends(get_db),
) -> CinodeResumePublicStatusResponse:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, token_override)

    try:
        result = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    selected_resume_id = result.get("selected_resume_id")
    selected_resume: dict | None = None
    resumes = result.get("resumes")
    if isinstance(resumes, list):
        for item in resumes:
            if not isinstance(item, dict):
                continue
            item_id = item.get("id")
            if item_id is not None and selected_resume_id is not None and int(item_id) == int(selected_resume_id):
                selected_resume = item
                break
        if selected_resume is None and resumes:
            first = resumes[0]
            if isinstance(first, dict):
                selected_resume = first

    public_url = None
    if selected_resume and isinstance(selected_resume.get("publicViewUrl"), str):
        public_url = selected_resume["publicViewUrl"].strip()

    ready, status_code, detail = check_public_resume_url(public_url or "")
    return CinodeResumePublicStatusResponse(
        credential_id=credential_id,
        consultant_id=consultant_id,
        resume_id=selected_resume_id,
        checked_url=public_url,
        public_ready=ready,
        status_code=status_code,
        detail=detail,
    )


@router.post(
    "/credentials/{credential_id}/browser-login",
    response_model=CinodeBrowserLoginResponse,
)
def login_cinode_browser(
    credential_id: str,
    company_slug: str = "xlent",
    db: Session = Depends(get_db),
) -> CinodeBrowserLoginResponse:
    settings = get_settings()
    if not settings.cinode_ui_automation_enabled:
        raise HTTPException(
            status_code=400,
            detail="Browser-automasjon er deaktivert. Sett CINODE_UI_AUTOMATION_ENABLED=true i .env.",
        )

    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")

    try:
        normalized_company = (company_slug or "xlent").strip().lower()
        if normalized_company not in {"xlent", "differ", "folden"}:
            normalized_company = "xlent"
        result = login_cinode_browser_profile(
            app_url=settings.cinode_app_url,
            company_slug=normalized_company,
            headless=settings.cinode_ui_headless,
            timeout_ms=settings.cinode_ui_timeout_ms,
        )
    except CinodeBrowserCreateCvError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return CinodeBrowserLoginResponse(
        ok=bool(result.get("ok")),
        detail=str(result.get("detail") or ""),
        current_url=result.get("current_url"),
        debug_trace=result.get("debug_trace") if isinstance(result.get("debug_trace"), list) else [],
    )


@router.post(
    "/credentials/{credential_id}/consultants/{consultant_id}/preflight-browser-access",
    response_model=CinodeBrowserPreflightResponse,
)
def preflight_consultant_browser_access(
    credential_id: str,
    consultant_id: str,
    payload: CinodeBrowserPreflightRequest,
    db: Session = Depends(get_db),
) -> CinodeBrowserPreflightResponse:
    settings = get_settings()
    if not settings.cinode_ui_automation_enabled:
        raise HTTPException(
            status_code=400,
            detail="Browser-automasjon er deaktivert. Sett CINODE_UI_AUTOMATION_ENABLED=true i .env.",
        )

    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, payload.cinode_token_override)

    try:
        consultant_data = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=payload.resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    selected_resume_id = consultant_data.get("selected_resume_id")
    if selected_resume_id is None:
        return CinodeBrowserPreflightResponse(
            ok=False,
            detail="Preflight feilet: fant ikke valgt utgangspunkt-CV for konsulenten.",
            consultant_id=consultant_id,
            resume_id=None,
            edit_url=None,
            current_url=None,
            debug_trace=[],
        )

    selected_resume_entry = _find_selected_resume_entry(consultant_data)
    if not selected_resume_entry:
        return CinodeBrowserPreflightResponse(
            ok=False,
            detail="Preflight feilet: valgt CV-id er ikke synlig i kandidatens resume-liste.",
            consultant_id=consultant_id,
            resume_id=int(selected_resume_id),
            edit_url=None,
            current_url=None,
            debug_trace=[],
        )

    try:
        result = preflight_cinode_resume_edit_access(
            app_url=settings.cinode_app_url,
            company_slug=(payload.company_slug or "xlent").strip().lower(),
            consultant_id=consultant_id,
            resume_id=int(selected_resume_id),
            resume_slug=str(selected_resume_entry.get("slug") or ""),
            owner_company_user_id=selected_resume_entry.get("companyUserId"),
            headless=settings.cinode_ui_headless,
            timeout_ms=min(settings.cinode_ui_timeout_ms, 90000),
        )
    except CinodeBrowserCreateCvError as exc:
        return CinodeBrowserPreflightResponse(
            ok=False,
            detail=f"Preflight feilet: {exc}",
            consultant_id=consultant_id,
            resume_id=int(selected_resume_id),
            edit_url=None,
            current_url=None,
            debug_trace=[],
        )

    return CinodeBrowserPreflightResponse(
        ok=bool(result.get("ok")),
        detail=str(result.get("detail") or ""),
        consultant_id=consultant_id,
        resume_id=int(selected_resume_id),
        edit_url=result.get("edit_url"),
        current_url=result.get("current_url"),
        debug_trace=result.get("debug_trace") if isinstance(result.get("debug_trace"), list) else [],
    )


@router.post(
    "/credentials/{credential_id}/consultants/{consultant_id}/create-cv-browser",
    response_model=CinodeBrowserCreateCvResponse,
)
def create_consultant_cv_via_browser(
    credential_id: str,
    consultant_id: str,
    payload: CinodeBrowserCreateCvRequest,
    db: Session = Depends(get_db),
) -> CinodeBrowserCreateCvResponse:
    settings = get_settings()
    if not settings.cinode_ui_automation_enabled:
        raise HTTPException(
            status_code=400,
            detail="Browser-automasjon er deaktivert. Sett CINODE_UI_AUTOMATION_ENABLED=true i .env.",
        )

    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, payload.cinode_token_override)

    variant = db.query(CvVariant).filter(CvVariant.id == payload.variant_id).first()
    if not variant:
        raise HTTPException(status_code=404, detail="CV variant not found")

    snapshot = db.query(ProfileSnapshot).filter(ProfileSnapshot.id == variant.base_snapshot_id).first()
    if not snapshot:
        raise HTTPException(status_code=404, detail="Base snapshot not found")

    suggestions = db.query(CvSuggestion).filter(CvSuggestion.variant_id == variant.id).all()
    accepted_suggestions = [s for s in suggestions if str(s.status or "").strip().lower() == "accepted"]
    accepted_keyword_terms = _collect_skill_terms_from_suggestions(suggestions)
    exportable_keyword_count = len(accepted_keyword_terms)
    cinode_payload = build_cinode_payload(snapshot.raw_payload_json, suggestions, include_pending=False)
    presentation_text = (payload.presentation_text_override or "").strip() or _compose_presentation_text(cinode_payload)
    title_used = (payload.title_override or "").strip() or variant.title

    try:
        consultant_data = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=payload.resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    seed_url: str | None = None
    selected_resume_id = consultant_data.get("selected_resume_id")
    resumes = consultant_data.get("resumes")
    if isinstance(resumes, list):
        for entry in resumes:
            if not isinstance(entry, dict):
                continue
            entry_id = entry.get("id")
            if entry_id is not None and selected_resume_id is not None and int(entry_id) == int(selected_resume_id):
                if isinstance(entry.get("viewUrl"), str) and entry["viewUrl"].strip():
                    seed_url = entry["viewUrl"].strip()
                    break
                if isinstance(entry.get("publicViewUrl"), str) and entry["publicViewUrl"].strip():
                    seed_url = entry["publicViewUrl"].strip()
                    break

    selected_resume_docx: bytes | None = None
    source_resume_skill_terms: list[str] = []
    if payload.enforce_selected_resume_source:
        if not isinstance(consultant_data.get("resume"), dict):
            raise HTTPException(
                status_code=400,
                detail=(
                    "Fant ikke valgt utgangspunkt-CV i Cinode-responsen. "
                    "Velg en konkret CV i dropdown og prøv igjen."
                ),
            )
        selected_resume_docx = build_cinode_cv_docx(
            profile=consultant_data.get("profile") if isinstance(consultant_data.get("profile"), dict) else {},
            resume=consultant_data.get("resume") if isinstance(consultant_data.get("resume"), dict) else None,
        )
        source_resume_skill_terms = _extract_skills_from_selected_resume(
            consultant_data.get("resume") if isinstance(consultant_data.get("resume"), dict) else None
        )

    # Safety-net: include accepted keyword terms when available, even if an old
    # frontend instance still posts apply_keywords=false.
    apply_keywords_effective = bool(payload.apply_keywords) or bool(accepted_keyword_terms)
    strict_mode_effective = bool(payload.strict_deterministic_mode)
    preflight_trace: list[str] = []

    # Prioriter nye/godkjente keyword-termer først.
    # Kilde-skills fra valgt CV trengs normalt ikke når vi kopierer valgt CV som basis.
    skills_keywords_to_apply: list[str] = []
    if apply_keywords_effective and accepted_keyword_terms:
        skills_keywords_to_apply.extend(accepted_keyword_terms)
    if (not payload.enforce_selected_resume_source) and source_resume_skill_terms:
        skills_keywords_to_apply.extend(source_resume_skill_terms)
    # de-dup while preserving order
    deduped_terms: list[str] = []
    seen_terms: set[str] = set()
    for term in skills_keywords_to_apply:
        key = str(term).strip().lower()
        if not key or key in seen_terms:
            continue
        seen_terms.add(key)
        deduped_terms.append(str(term).strip())
    skills_keywords_to_apply = deduped_terms[:80]

    title_used = _ensure_unique_resume_title(title_used, resumes if isinstance(resumes, list) else None)
    docx_bytes = build_docx_from_payload(title=title_used, payload=cinode_payload)

    if strict_mode_effective:
        if selected_resume_id is None:
            raise HTTPException(
                status_code=400,
                detail=(
                    "Preflight feilet: ingen valgt utgangspunkt-CV (resume_id). "
                    "Velg en konkret CV i dropdown og prøv igjen."
                ),
            )
        selected_resume_entry = _find_selected_resume_entry(consultant_data)
        if not selected_resume_entry:
            raise HTTPException(
                status_code=400,
                detail=(
                    "Preflight feilet: valgt utgangspunkt-CV ble ikke funnet i kandidatens resume-liste. "
                    "Velg CV på nytt og prøv igjen."
                ),
            )
        try:
            preflight = preflight_cinode_resume_edit_access(
                app_url=settings.cinode_app_url,
                company_slug=(payload.company_slug or "xlent").strip().lower(),
                consultant_id=consultant_id,
                resume_id=int(selected_resume_id),
                resume_slug=str(selected_resume_entry.get("slug") or ""),
                owner_company_user_id=selected_resume_entry.get("companyUserId"),
                headless=settings.cinode_ui_headless,
                timeout_ms=min(settings.cinode_ui_timeout_ms, 90000),
            )
        except CinodeBrowserCreateCvError as exc:
            raise HTTPException(status_code=400, detail=f"Preflight feilet: {exc}") from exc
        preflight_trace = preflight.get("debug_trace") if isinstance(preflight.get("debug_trace"), list) else []
        if not preflight.get("ok"):
            detail = str(preflight.get("detail") or "Preflight feilet uten detalj.")
            if preflight_trace:
                detail = f"{detail} Trace: {' | '.join(preflight_trace[:30])}"
            raise HTTPException(status_code=400, detail=detail)

    try:
        normalized_company = (payload.company_slug or "xlent").strip().lower()
        if normalized_company not in {"xlent", "differ", "folden"}:
            normalized_company = "xlent"
        template_map = {
            "xlent": "XLENT",
            "differ": "Differ",
            "folden": "Folden",
        }
        result = create_cinode_cv_via_browser(
            app_url=settings.cinode_app_url,
            consultant_id=consultant_id,
            consultant_name=consultant_data.get("full_name") or consultant_id,
            title=title_used,
            docx_bytes=docx_bytes,
            presentation_text=presentation_text,
            skills_keywords=skills_keywords_to_apply,
            resume_seed_url=seed_url,
            source_resume_id=selected_resume_id,
            company_slug=normalized_company,
            preferred_template_keyword=template_map.get(normalized_company, "XLENT"),
            clean_new_cv_content=bool(payload.clean_new_cv_content),
            source_resume_docx_bytes=selected_resume_docx,
            require_source_docx_import=bool(payload.enforce_selected_resume_source),
            headless=settings.cinode_ui_headless,
            timeout_ms=settings.cinode_ui_timeout_ms,
            strict_deterministic_mode=strict_mode_effective,
            cinode_api_base_url=row.base_url,
            cinode_api_auth_value=auth_value,
            cinode_company_id=str(consultant_data.get("company_id") or ""),
        )
    except CinodeBrowserCreateCvError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    if preflight_trace:
        existing = result.get("debug_trace")
        if not isinstance(existing, list):
            existing = []
        result["debug_trace"] = [f"PRECHECK: {entry}" for entry in preflight_trace] + existing

    if result.get("ok"):
        variant.status = "exported"
        db.commit()

    return CinodeBrowserCreateCvResponse(
        ok=bool(result.get("ok")),
        mode=str(result.get("mode") or "browser_automation"),
        detail=(
            f"{str(result.get('detail') or '')} "
            f"(Forslag brukt i eksport: {len(accepted_suggestions)} "
            f"[godkjente: {len(accepted_suggestions)}], keyword brukt: {exportable_keyword_count}, "
            f"kilde-skills kopiert: {len(source_resume_skill_terms)}, "
            f"skills forsøkt lagt inn: {len(skills_keywords_to_apply)}, "
            f"tekstkilde: {'ui_override' if (payload.presentation_text_override or '').strip() else 'variant_summary'}, "
            f"keyword-innsetting: {'på' if apply_keywords_effective else 'av'} "
            f"(request: {'på' if payload.apply_keywords else 'av'}), "
            f"clean-mode: {'på' if payload.clean_new_cv_content else 'av'}, "
            f"kilde-CV-lås: {'på' if payload.enforce_selected_resume_source else 'av'}, "
            f"strict deterministic mode: {'på' if strict_mode_effective else 'av'}, "
            f"tekstfingerprint: {_payload_fingerprint(presentation_text)}, "
            f"resume_seed_id: {selected_resume_id}, title_used: '{title_used}')"
        ).strip(),
        title_used=title_used,
        target_url=result.get("target_url"),
        created_resume_url=result.get("created_resume_url"),
        screenshot_path=result.get("screenshot_path"),
        debug_trace=result.get("debug_trace") if isinstance(result.get("debug_trace"), list) else [],
    )


@router.get("/credentials/{credential_id}/consultants/{consultant_id}/enrich", response_model=CinodeConsultantEnrichResponse)
def enrich_consultant(
    credential_id: str,
    consultant_id: str,
    resume_id: int | None = None,
    token_override: str | None = None,
    db: Session = Depends(get_db),
) -> CinodeConsultantEnrichResponse:
    row = db.query(CinodeCredential).filter(CinodeCredential.id == credential_id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Credential not found")
    auth_value = _resolve_auth_value(row, token_override)

    try:
        result = fetch_cinode_consultant_cv(
            base_url=row.base_url,
            auth_value=auth_value,
            consultant_id=consultant_id,
            resume_id=resume_id,
        )
    except CinodeApiError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    enriched = enrich_consultant_data(
        full_name=result.get("full_name") or "",
        profile_payload=result.get("profile") if isinstance(result.get("profile"), dict) else None,
        resume_payload=result.get("resume") if isinstance(result.get("resume"), dict) else None,
    )

    return CinodeConsultantEnrichResponse(
        credential_id=credential_id,
        consultant_id=consultant_id,
        resume_id=result.get("selected_resume_id"),
        full_name=result.get("full_name") or consultant_id,
        linkedin_url=enriched.get("linkedin_url"),
        linkedin_profile_text=enriched.get("linkedin_profile_text"),
        github_url=enriched.get("github_url"),
        orcid_url=enriched.get("orcid_url"),
        researchgate_url=enriched.get("researchgate_url"),
        scholar_url=enriched.get("scholar_url"),
        scholar_publications=enriched.get("scholar_publications") or [],
        candidate_facts=enriched.get("candidate_facts") or [],
        external_findings=enriched.get("external_findings") or [],
        sources=enriched.get("sources") or [],
        warnings=enriched.get("warnings") or [],
    )
